### PR TITLE
search with units only if units

### PR DESCRIPTION
**Pull request by antoine-de**
linked to https://github.com/pelias/pelias/issues/690

Note: is the query's `_name` important ?
I used the same `_name` for `createUnitAndAddressShould` and `createAddressShould` like it's done in https://github.com/pelias/query/blob/master/layout/StructuredFallbackQuery.js#L188 not sure if that's right

### CODE REVIEW

**Review by trescube — CHANGES_REQUESTED** [review]
Could you add tests for this new condition?

**Comment by antoine-de** [comment]
oups sorry, tests added.

I also added a test with a unit and no housenumber (in that case, we don't use the unit, only search with the street) since it's the current behavior.

Tell me if that is not OK (not very familiar with `units` that does not exist in france :smile: )

**Comment by sweco-semhul** [comment]
looks good to me, thanks for fixing this.

**Comment by trescube** [comment]
Sorry, got distracted.  Looks great!

**Review by trescube — APPROVED** [review]

**Pull request merged**
