### PR TITLE
remove references to deprecated property _cache

### PR DESCRIPTION
**Pull request by missinglink**
the `_cache` key has been deprecated in ES2+ as per: https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_query_dsl_changes.html#_filter_auto_caching

see also: https://github.com/elastic/elasticsearch/issues/16441

Connects pelias/pelias#325

### CODE REVIEW

**Comment by orangejulius** [comment]
Is this ES 1.7 compatible? If not is there a way to make our queries ES 1.7 and 2.x compatible at the same time? As listed in the [Upgrade to Elasticsearch 2](https://github.com/pelias/pelias/issues/325) plan, it would be nice if as much work as possible is done beforehand to minimize the amount of stuff that has to change when we actually switch over.

**Comment by orangejulius** [comment]
LGTM

**Comment by dianashk** [comment]
:shipit:

**Comment by orangejulius** [comment]
:shipit:

**Pull request merged**
