### PR TITLE
Category filter

### PR DESCRIPTION
**Pull request by jthi3rry**
We'd like to be able to filter places via their categories, and this would be a pre-requisite for the Pelias API.

### CODE REVIEW

**Comment by dianashk** [comment]
@jthi3rry, thanks for the PR. We had category support in the Beta, but weren't ready to commit to a taxonomy for the 1.0 release, so we pulled the code out. This is definitely going to help once we're ready to bring it back in. 

If you're running your own instance of Pelias, we'd love to hear more about your use-case and your thoughts on category taxonomy. Thanks.

**Comment by jthi3rry** [comment]
Hi @dianashk,

Thanks for clarifying the state of categories, I wasn't too sure as I saw a couple of things in the API around categories that were disconnected (e.g. `sanitiser/_categories.js`).

We mostly intend to use categories as tags, to be able to filter places when geo-coding (e.g. reverse geo-code to a place tagged as a metropolitan area). The main advantage we found with Pelias and Elasticsearch is that we can create our own taxonomy by extending your importers or updating the documents to support our needs, and then use the category filter (which could be renamed `tags` to carry the meaning that it's not a clearly defined taxonomy?).

The second reason we looked into this is because the API layers don't really map well with geonames, where everything seems to be a `venue`, and we weren't able to search by country, region or city so ended up adding these as categories. (https://github.com/predicthq/pelias-api/pull/1)

BTW, the layers also cause issues with the `gid`, e.g. New Zealand's gid when geo-coding is `gn:neighbourhood:2186224`, and the `place` endpoint will only accept `gn:venue:2186224`.

The mapping we use is as follows (https://github.com/predicthq/pelias-geonames/pull/1):
- `country`: PCL, PCLD, PCLF, PCLI, PCLIX, PCLS
- `region`: ADM1
- `county`: ADM2
- `localadmin`: ADM3, ADM4, ADM5
- `locality`: PPL, PPLA, PPLA2, PPLA3, PPLA4, PPLC, PPLL, PPLG, PPLQ, PPLS
- `neighbourhood`: PPLX, PPLF

With some extras:
- `continent`: CONT
- `planet`: geonameid:6295630 (Earth)

This mapping is probably not perfect, but having the ability to create it, add our own tags and filter on them is great, and without committing to a taxonomy, keeping the feature in the API (maybe with empty categories by default?) would be very useful to us.

**Comment by dianashk** [comment]
@jthi3rry, you're totally right about the `geonames` mappings being problematic. This, in turn, is causing the `/place` lookup by id to fail, as you also pointed out. We'll be working on resolving that as part of our move away from `geonames` and `quattroshapes` and towards the new [Mapzen **Who'sOnFirst**](https://github.com/whosonfirst/whosonfirst-data) data set. 

We'll discuss in our next planning meeting whether or not this can be merged and still turned off at the API level, but at least allow you guys to not have to point to a github branch in your `package.json`, nobody likes having to do that.

Thanks for giving us some insight into your usecase. Keep the feedback and pull requests coming. :grinning:

**Comment by dianashk** [comment]
Hey @jthi3rry, we just discussed this PR with the team and we'd be happy to merge it. :smiley: 

Would you have a little time to add some tests to this?
Would be great to see one [here](https://github.com/pelias/query/blob/master/test/lib/Variable.js#L44) validating that `array` type is supported.
Maybe check [here](https://github.com/pelias/query/blob/master/test/lib/Variable.js#L93) that `toString` and `toJSON` functions work for `array` types as well.

Much appreciated.

**Comment by jthi3rry** [comment]
Hi @dianashk, sorry for the delay and thanks for the pointers to the right places in tests. Please see the updated commit. Let me know if you can think of other changes. :-)

**Comment by dianashk** [comment]
Will need to update the version in API package.json after this is published to npm.

**Comment by dianashk** [comment]
Hey @jthi3rry, great news! We're finally reimplementing the `categories` filter and would like to merge your work. I've created a new PR that should have all of your changes in it. Just giving you a heads up that it will hopefully be merged in the next couple of weeks.

If you'd like to follow our progress keep an eye on pelias/pelias#150 and all connected PRs.
The PR replacing this one is #24.

**Comment by dianashk** [comment]
The [replacement PR](#24) has finally been merged so this can be closed. Thanks all for your patience.

**Pull request closed without merging**
