### PR TITLE
Use cutoff_frequency everywhere

### PR DESCRIPTION
**Pull request by orangejulius**
Allow query views to set the [cutoff_frequency](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-match-query.html#query-dsl-match-query-cutoff) feature to support better performance on queries with lots of high-frequency terms.

See https://github.com/pelias/api/pull/1213 for more explanation on the use cases.

### CODE REVIEW

**Comment by missinglink** [comment]
@orangejulius I have actioned the todo's you noted above, the extra commit modifies the behaviour of `cutoff_frequency` so that it can be defined on a per-field basis for sub-properties of `address` and `admin`.

**Comment by missinglink** [comment]
This is good to merge, we just need to be careful that default values are set for each possible property combination before merging or the views will start failing.

**Review by missinglink — APPROVED** [review]
Good-to-merge pending default values being set for these properties in `pelias/api`.

**Comment by orangejulius** [comment]
Nice, thanks. Another option is to make this PR a noop if those values aren't defined. Then we could merge it immediately and handle the rest in API.

**Comment by missinglink** [comment]
Good call, I've added another commit which now makes `cutoff_frquency` optional, when not defined it simply doesn't add that property to the query.

**Comment by missinglink** [comment]
@orangejulius feel free to merge this if you're happy with it.

**Comment by orangejulius** [comment]
I've added to the last commit to make `cutoff_frequency` optional everywhere, and in my testing this PR is indeed a noop on pelias/api.

**Pull request merged**
